CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20240403010337_InitialMigration') THEN
    CREATE TABLE urls (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        short character(7) NOT NULL,
        long_url text NOT NULL,
        created_at timestamp with time zone NOT NULL,
        CONSTRAINT "PK_id" PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20240403010337_InitialMigration') THEN
    CREATE UNIQUE INDEX "IX_short" ON urls (short);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20240403010337_InitialMigration') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20240403010337_InitialMigration', '8.0.3');
    END IF;
END $EF$;
COMMIT;

