name: Build and push Docker image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    name: Build and push Docker image to GitHub Registry
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      packages: write
      id-token: write

    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: ${{ github.repository }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Authenticate to GitHub Registry
        uses: 'docker/login-action@v1'
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build Docker image
        run: docker image build -t "${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}" .

      - name: Push Docker image to Google Cloud Artifact Registry
        run: docker image push "${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}"
